### ISSUE TITLE
compatibility problems with Plone 5.1b2?

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.plonetruegallery#58]
```$ bin/buildout
]133;C;Upgraded:
  zc.buildout version 2.8.0,
  setuptools version 34.3.0;
restarting.
Generated script '/Users/kim/PloneBuilds/Plone-5.1b2/simple-plone-buildout/bin/buildout'.
Develop: '/Users/kim/PloneBuilds/Plone-5.1b2/simple-plone-buildout/src/collective.plonetruegallery'
Traceback (most recent call last):
  File "/var/folders/nz/x0t781tx0674r3h71hg19jk80000gn/T/tmpuvyvpL", line 6, in <module>
    import os, setuptools
  File "/Users/kim/.buildout/eggs/setuptools-34.3.0-py2.7.egg/setuptools/__init__.py", line 10, in <module>
    from six.moves import filter, map
ImportError: No module named six.moves
While:
  Installing.
  Processing develop directory '/Users/kim/PloneBuilds/Plone-5.1b2/simple-plone-buildout/src/collective.plonetruegallery'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/kim/PloneBuilds/Plone-5.1b2/simple-plone-buildout/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1995, in main
    getattr(buildout, command)(args)
  File "/Users/kim/PloneBuilds/Plone-5.1b2/simple-plone-buildout/lib/python2.7/site-packages/zc/buildout/buildout.py", line 528, in install
    installed_develop_eggs = self._develop()
  File "/Users/kim/PloneBuilds/Plone-5.1b2/simple-plone-buildout/lib/python2.7/site-packages/zc/buildout/buildout.py", line 770, in _develop
    zc.buildout.easy_install.develop(setup, dest)
  File "/Users/kim/PloneBuilds/Plone-5.1b2/simple-plone-buildout/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 1020, in develop
    call_subprocess(args)
  File "/Users/kim/PloneBuilds/Plone-5.1b2/simple-plone-buildout/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 160, in call_subprocess
    % repr(args)[1:-1])
Exception: Failed to run command:
'/Users/kim/PloneBuilds/Plone-5.1b2/simple-plone-buildout/bin/python', '/var/folders/nz/x0t781tx0674r3h71hg19jk80000gn/T/tmpuvyvpL', '-q', 'develop', '-mN', '-d', '/Users/kim/PloneBuilds/Plone-5.1b2/simple-plone-buildout/develop-eggs/tmpmYBQRtbuild'```

**Comment by tkimnguyen** [comment]
This doesn't happen with Plone 5.1.4 so closing
